(Background on this error at: https://sqlalche.me/e/20/f405) [in /app/photovault/routes/mobile_api.py:324]
FROM photo 
WHERE photo.user_id = %(user_id_1)s) AS anon_1]
ERROR:photovault.routes.mobile_api:Dashboard error: (psycopg2.errors.UndefinedColumn) column photo.original_photo_id does not exist
LINE 2: ...oto_id, photo.is_back_side AS photo_is_back_side, photo.orig...
                                                             ^
[SQL: SELECT count(*) AS count_1 
FROM (SELECT photo.id AS photo_id, photo.filename AS photo_filename, photo.original_name AS photo_original_name, photo.file_path AS photo_file_path, photo.thumbnail_path AS photo_thumbnail_path, photo.file_size AS photo_file_size, photo.width AS photo_width, photo.height AS photo_height, photo.mime_type AS photo_mime_type, photo.upload_source AS photo_upload_source, photo.created_at AS photo_created_at, photo.updated_at AS photo_updated_at, photo.user_id AS photo_user_id, photo.album_id AS photo_album_id, photo.photo_date AS photo_photo_date, photo.date_text AS photo_date_text, photo.date_circa AS photo_date_circa, photo.location_text AS photo_location_text, photo.occasion AS photo_occasion, photo.condition AS photo_condition, photo.photo_source AS photo_photo_source, photo.back_text AS photo_back_text, photo.needs_restoration AS photo_needs_restoration, photo.auto_enhanced AS photo_auto_enhanced, photo.processing_notes AS photo_processing_notes, photo.edited_filename AS photo_edited_filename, photo.edited_path AS photo_edited_path, photo.enhancement_metadata AS photo_enhancement_metadata, photo.paired_photo_id AS photo_paired_photo_id, photo.is_back_side AS photo_is_back_side, photo.original_photo_id AS photo_original_photo_id, photo.is_enhanced_version AS photo_is_enhanced_version, photo.enhancement_type AS photo_enhancement_type 
[parameters: {'user_id_1': 2}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2025-10-28 03:02:36,566] ERROR in gallery: Error serving file avatar_20251019_042037.jpg for user 2: (psycopg2.errors.UndefinedColumn) column photo.original_photo_id does not exist
LINE 1: ...oto_id, photo.is_back_side AS photo_is_back_side, photo.orig...
                                                             ^
[SQL: SELECT photo.id AS photo_id, photo.filename AS photo_filename, photo.original_name AS photo_original_name, photo.file_path AS photo_file_path, photo.thumbnail_path AS photo_thumbnail_path, photo.file_size AS photo_file_size, photo.width AS photo_width, photo.height AS photo_height, photo.mime_type AS photo_mime_type, photo.upload_source AS photo_upload_source, photo.created_at AS photo_created_at, photo.updated_at AS photo_updated_at, photo.user_id AS photo_user_id, photo.album_id AS photo_album_id, photo.photo_date AS photo_photo_date, photo.date_text AS photo_date_text, photo.date_circa AS photo_date_circa, photo.location_text AS photo_location_text, photo.occasion AS photo_occasion, photo.condition AS photo_condition, photo.photo_source AS photo_photo_source, photo.back_text AS photo_back_text, photo.needs_restoration AS photo_needs_restoration, photo.auto_enhanced AS photo_auto_enhanced, photo.processing_notes AS photo_processing_notes, photo.edited_filename AS photo_edited_filename, photo.edited_path AS photo_edited_path, photo.enhancement_metadata AS photo_enhancement_metadata, photo.paired_photo_id AS photo_paired_photo_id, photo.is_back_side AS photo_is_back_side, photo.original_photo_id AS photo_original_photo_id, photo.is_enhanced_version AS photo_is_enhanced_version, photo.enhancement_type AS photo_enhancement_type 
FROM photo 
WHERE photo.user_id = %(user_id_1)s AND (photo.filename = %(filename_1)s OR photo.edited_filename = %(edited_filename_1)s) 
 LIMIT %(param_1)s]
[parameters: {'user_id_1': 2, 'filename_1': 'avatar_20251019_042037.jpg', 'edited_filename_1': 'avatar_20251019_042037.jpg', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-10-28 03:02:36,566 ERROR: Error serving file avatar_20251019_042037.jpg for user 2: (psycopg2.errors.UndefinedColumn) column photo.original_photo_id does not exist
LINE 1: ...oto_id, photo.is_back_side AS photo_is_back_side, photo.orig...
                                                             ^
[SQL: SELECT photo.id AS photo_id, photo.filename AS photo_filename, photo.original_name AS photo_original_name, photo.file_path AS photo_file_path, photo.thumbnail_path AS photo_thumbnail_path, photo.file_size AS photo_file_size, photo.width AS photo_width, photo.height AS photo_height, photo.mime_type AS photo_mime_type, photo.upload_source AS photo_upload_source, photo.created_at AS photo_created_at, photo.updated_at AS photo_updated_at, photo.user_id AS photo_user_id, photo.album_id AS photo_album_id, photo.photo_date AS photo_photo_date, photo.date_text AS photo_date_text, photo.date_circa AS photo_date_circa, photo.location_text AS photo_location_text, photo.occasion AS photo_occasion, photo.condition AS photo_condition, photo.photo_source AS photo_photo_source, photo.back_text AS photo_back_text, photo.needs_restoration AS photo_needs_restoration, photo.auto_enhanced AS photo_auto_enhanced, photo.processing_notes AS photo_processing_notes, photo.edited_filename AS photo_edited_filename, photo.edited_path AS photo_edited_path, photo.enhancement_metadata AS photo_enhancement_metadata, photo.paired_photo_id AS photo_paired_photo_id, photo.is_back_side AS photo_is_back_side, photo.original_photo_id AS photo_original_photo_id, photo.is_enhanced_version AS photo_is_enhanced_version, photo.enhancement_type AS photo_enhancement_type 
FROM photo 
WHERE photo.user_id = %(user_id_1)s AND (photo.filename = %(filename_1)s OR photo.edited_filename = %(edited_filename_1)s) 
 LIMIT %(param_1)s]
[parameters: {'user_id_1': 2, 'filename_1': 'avatar_20251019_042037.jpg', 'edited_filename_1': 'avatar_20251019_042037.jpg', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405) [in /app/photovault/routes/gallery.py:614]
2025-10-28 03:02:36,566 ERROR: Error serving file avatar_20251019_042037.jpg for user 2: (psycopg2.errors.UndefinedColumn) column photo.original_photo_id does not exist
LINE 1: ...oto_id, photo.is_back_side AS photo_is_back_side, photo.orig...
                                                             ^
[SQL: SELECT photo.id AS photo_id, photo.filename AS photo_filename, photo.original_name AS photo_original_name, photo.file_path AS photo_file_path, photo.thumbnail_path AS photo_thumbnail_path, photo.file_size AS photo_file_size, photo.width AS photo_width, photo.height AS photo_height, photo.mime_type AS photo_mime_type, photo.upload_source AS photo_upload_source, photo.created_at AS photo_created_at, photo.updated_at AS photo_updated_at, photo.user_id AS photo_user_id, photo.album_id AS photo_album_id, photo.photo_date AS photo_photo_date, photo.date_text AS photo_date_text, photo.date_circa AS photo_date_circa, photo.location_text AS photo_location_text, photo.occasion AS photo_occasion, photo.condition AS photo_condition, photo.photo_source AS photo_photo_source, photo.back_text AS photo_back_text, photo.needs_restoration AS photo_needs_restoration, photo.auto_enhanced AS photo_auto_enhanced, photo.processing_notes AS photo_processing_notes, photo.edited_filename AS photo_edited_filename, photo.edited_path AS photo_edited_path, photo.enhancement_metadata AS photo_enhancement_metadata, photo.paired_photo_id AS photo_paired_photo_id, photo.is_back_side AS photo_is_back_side, photo.original_photo_id AS photo_original_photo_id, photo.is_enhanced_version AS photo_is_enhanced_version, photo.enhancement_type AS photo_enhancement_type 
FROM photo 
WHERE photo.user_id = %(user_id_1)s AND (photo.filename = %(filename_1)s OR photo.edited_filename = %(edited_filename_1)s) 
 LIMIT %(param_1)s]
[parameters: {'user_id_1': 2, 'filename_1': 'avatar_20251019_042037.jpg', 'edited_filename_1': 'avatar_20251019_042037.jpg', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405) [in /app/photovault/routes/gallery.py:614]
ERROR:photovault:Error serving file avatar_20251019_042037.jpg for user 2: (psycopg2.errors.UndefinedColumn) column photo.original_photo_id does not exist
LINE 1: ...oto_id, photo.is_back_side AS photo_is_back_side, photo.orig...
                                                             ^
[SQL: SELECT photo.id AS photo_id, photo.filename AS photo_filename, photo.original_name AS photo_original_name, photo.file_path AS photo_file_path, photo.thumbnail_path AS photo_thumbnail_path, photo.file_size AS photo_file_size, photo.width AS photo_width, photo.height AS photo_height, photo.mime_type AS photo_mime_type, photo.upload_source AS photo_upload_source, photo.created_at AS photo_created_at, photo.updated_at AS photo_updated_at, photo.user_id AS photo_user_id, photo.album_id AS photo_album_id, photo.photo_date AS photo_photo_date, photo.date_text AS photo_date_text, photo.date_circa AS photo_date_circa, photo.location_text AS photo_location_text, photo.occasion AS photo_occasion, photo.condition AS photo_condition, photo.photo_source AS photo_photo_source, photo.back_text AS photo_back_text, photo.needs_restoration AS photo_needs_restoration, photo.auto_enhanced AS photo_auto_enhanced, photo.processing_notes AS photo_processing_notes, photo.edited_filename AS photo_edited_filename, photo.edited_path AS photo_edited_path, photo.enhancement_metadata AS photo_enhancement_metadata, photo.paired_photo_id AS photo_paired_photo_id, photo.is_back_side AS photo_is_back_side, photo.original_photo_id AS photo_original_photo_id, photo.is_enhanced_version AS photo_is_enhanced_version, photo.enhancement_type AS photo_enhancement_type 
FROM photo 
WHERE photo.user_id = %(user_id_1)s AND (photo.filename = %(filename_1)s OR photo.edited_filename = %(edited_filename_1)s) 
 LIMIT %(param_1)s]
[parameters: {'user_id_1': 2, 'filename_1': 'avatar_20251019_042037.jpg', 'edited_filename_1': 'avatar_20251019_042037.jpg', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2025-10-28 03:02:36,566] WARNING in gallery: Serving placeholder due to exception: avatar_20251019_042037.jpg
2025-10-28 03:02:36,566 WARNING: Serving placeholder due to exception: avatar_20251019_042037.jpg [in /app/photovault/routes/gallery.py:616]
2025-10-28 03:02:36,566 WARNING: Serving placeholder due to exception: avatar_20251019_042037.jpg [in /app/photovault/routes/gallery.py:616]
WARNING:photovault:Serving placeholder due to exception: avatar_20251019_042037.jpg